version: '3'
services:
  web:
    build:
      context: .
    image: kanka
    container_name: kanka
    env_file:
      - .docker/web/variables.env
    restart: ${RESTART_POLICY}
    environment:
      APP_DEBUG: ${APP_DEBUG}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
      DB_HOST: database
      # DB_CONNECTION: mysql
      # DB_DATABASE: kanka_test
      # DB_USERNAME: homestead
      # DB_PASSWORD: secret
      REDIS_HOST: redis
      VIRUTAL_HOST: ${DOMAIN}
      LETSENCRYP_HOST: ${DOMAIN}
    depends_on:
      - database
      - redis
    networks:
      - web
      - database
  database:
    image: mariadb:10
    restart: ${RESTART_POLICY}
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ${DATA_MARIADB}:/var/lib/mysql
    networks:
      - database
  redis:
    image: redis
    restart: ${RESTART_POLICY}
    volumes:
      - ${DATA_REDIS}:/data
    networks:
      - database
  redirect:
    image: morbz/docker-web-redirect
    restart: ${RESTART_POLICY}
    logging:
      driver: ${LOGGING}
    environment:
      - VIRTUAL_HOST=${DOMAIN_ALT}
      - LETSENCRYPT_HOST=${DOMAIN_ALT}
      - REDIRECT_TARGET=${DOMAIN}
    networks:
      - web
networks:
  web:
    external:
      name: web
  database:
    drive: bridge
